service: pibot
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
plugins:
  - serverless-offline
  - serverless-s3-local
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: incoming
          method: post
